# Generated by Django 4.0.1 on 2022-01-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('W11', 'Windows 11'), ('W10', 'Windows 10'), ('W7', 'Windows 7'), ('M', 'Mac'), ('XSX', 'XBox Series X'), ('XSS', 'XBox Series S'), ('XOS', 'XBox One S'), ('XOX', 'XBox One X'), ('XO', 'XBox One'), ('X36', 'XBox 360'), ('X', 'XBox'), ('PS5', 'Playstation 5'), ('PS4', 'Playstation 4'), ('PS3', 'Playstation 3'), ('PS2', 'Playstation 2'), ('PS1', 'Playstation 1'), ('NS', 'Nintendo Switch'), ('WiU', 'Wii U'), ('Wii', 'Wii'), ('NGC', 'Nintendo GameCube'), ('N64', 'Nintendo 64'), ('iOS', 'iOS'), ('And', 'Android')], max_length=3)),
                ('release_date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Playhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('playtime', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
            ],
        ),
    ]
