# Generated by Django 4.0.1 on 2022-01-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_release_playhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='date',
            field=models.DateField(verbose_name='Play Date'),
        ),
        migrations.AlterField(
            model_name='playhistory',
            name='playtime',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
