# Generated by Django 4.0.1 on 2022-01-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_playhistory_playtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhistory',
            name='playtime',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
