# Generated by Django 4.0.1 on 2022-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_release_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
