# Generated by Django 4.0.1 on 2022-01-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_release_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='platform',
        ),
    ]
